heat_template_version: 2015-04-30

description: >
  A HOT template that holds a VM instance install Apache and creates a
  security group.

parameters:
  key_name:
    type: string
    description: Name of an existing key pair to use for the instance
    constraints:
      - custom_constraint: nova.keypair
        description: Must name a public key (pair) known to Nova
  flavor:
    type: string
    description: Flavor for the instance to be created
    default: m1.small
    constraints:
      - custom_constraint: nova.flavor
        description: Must be a flavor known to Nova
  image:
    type: string
    description: >
      Name or ID of the image to use for the instance.
      You can get the default from
      http://cloud.fedoraproject.org/fedora-20.x86_64.qcow2
      There is also
      http://cloud.fedoraproject.org/fedora-20.i386.qcow2
      Any image should work since this template
      does not ask the VM to do anything.
    constraints:
      - custom_constraint: glance.image
        description: Must identify an image known to Glance
  private_net_id:
    type: string
    description: ID of private network into which servers get deployed
    constraints:
      - custom_constraint: neutron.network
  private_subnet_id:
    type: string
    description: ID of private sub network into which servers get deployed

resources:
  configuration:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
        #!/bin/bash -v
        apt-get update
        apt-get -q -y upgrade
        apt-get -y install apache2 git
        apt-get -y install php5 libapache2-mod-php5 php5-mcrypt
        service apache2 restart

  my_instance:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      user_data_format: SOFTWARE_CONFIG
      user_data: {get_resource: configuration}
      networks:
        - port: { get_resource: my_instance_port }

  my_instance_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net_id }
      fixed_ips:
        - subnet_id: { get_param: private_subnet_id }
      security_groups: [{ get_resource: server_security_group }]

  server_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Add security group rules for server
      name: api-group
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 80
          port_range_max: 80
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 443
          port_range_max: 443

outputs:
  instance_networks:
    description: The IP addresses of the deployed instance
    value: { get_attr: [my_instance, networks] }
